language: node_js
node_js:
  - "11.14.0"
  - "lts/*"

before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1

before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - chmod +x .github/travis/success.sh
  - ./.github/travis/success.sh
after_failure:
  - chmod +x .github/travis/fail.sh
  - ./.github/travis/fail.sh
install: npm install
